version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz

brews:
  - repository:
      owner: smauermann
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/smauermann/skillex
    description: TUI for browsing and reading installed Claude Code skills
    license: MIT
    test: |
      assert_match "Error discovering skills", shell_output("#{bin}/skillex 2>&1", 1)
